# Generated by Django 4.2 on 2026-02-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttextcontent',
            name='text_content',
            field=models.TextField(blank=True, null=True, verbose_name='Текстовое содержание продукта'),
        ),
    ]
