# Generated by Django 4.2 on 2026-02-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказа'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('canceled', 'Отменен'), ('completed', 'Завершен'), ('refunded', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
