# Generated by Django 4.2 on 2026-02-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authcode',
            options={'verbose_name': 'Код аутентификации', 'verbose_name_plural': 'Коды аутентификации'},
        ),
        migrations.AlterModelOptions(
            name='buyerprofile',
            options={'verbose_name': 'Профиль покупателя', 'verbose_name_plural': 'Профили покупателей'},
        ),
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'verbose_name': 'Профиль продавца', 'verbose_name_plural': 'Профили продавцов'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
