# Generated by Django 4.2 on 2026-02-03 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название магазина')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг магазина')),
                ('description', models.TextField(blank=True, verbose_name='Описание магазина')),
                ('logo', models.ImageField(blank=True, default='stores/logos/default_logo.png', null=True, upload_to='stores/logos/', verbose_name='Логотип магазина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='Владелец магазина')),
            ],
        ),
    ]
