# Generated by Django 4.2 on 2026-02-03 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='Всего продаж')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('recalculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний пересчёт')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Статистика магазина',
                'verbose_name_plural': 'Статистика магазинов',
            },
        ),
    ]
