# Generated by Django 4.2 on 2026-02-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_storestats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
    ]
