# Generated by Django 4.2 on 2026-02-27 14:54

import apps.stores.models.store
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, default='stores/logos/default_logo.png', help_text='Рекомендуемый формат: PNG/JPG. Размер до 1 МБ. Пропорции 1:1 или 4:3.', null=True, upload_to=apps.stores.models.store.Store.logo_upload_path, verbose_name='Логотип магазина'),
        ),
    ]
